export const CHAR_PLAYER = '@'
export const CHAR_WALL = '#'
export const CHAR_FLOOR = '.'
export const CHAR_MONSTER = 'm'
export const CHAR_STAIRS_DOWN = '>'
export const CHAR_POTION = '!'
export const CHAR_WIN = '$'
export const CHAR_DEAD = '0'
